#!/bin/bash

echo "🌍 添加本地化支持到 Xcode 项目"
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1️⃣  在 Xcode 中打开项目："
echo "   open SmthApp.xcworkspace"
echo ""
echo "2️⃣  在左侧项目导航器中，选择 SmthApp 文件夹"
echo ""
echo "3️⃣  右键点击 SmthApp 文件夹，选择 'Add Files to \"SmthApp\"...'"
echo ""
echo "4️⃣  导航到以下文件夹并添加 InfoPlist.strings 文件："
echo "   - SmthApp/en.lproj/InfoPlist.strings"
echo "   - SmthApp/zh-Hans.lproj/InfoPlist.strings"
echo ""
echo "   ⚠️  确保勾选 'Copy items if needed' 和 'Add to targets: SmthApp'"
echo ""
echo "5️⃣  添加后，在左侧找到 InfoPlist.strings 文件"
echo ""
echo "6️⃣  选中 InfoPlist.strings，在右侧 File Inspector 中："
echo "   - 点击 'Localize...'"
echo "   - 选择 'English' 并点击 'Localize'"
echo "   - 然后勾选 'Simplified Chinese (zh-Hans)'"
echo ""
echo "7️⃣  清理项目并重新编译："
echo "   Product > Clean Build Folder (Shift+Cmd+K)"
echo "   Product > Build (Cmd+B)"
echo ""
echo "✅ 完成后，应用名称将根据系统语言自动切换！"
echo ""
